#!/bin/zsh

if ! ([[ -n $1 ]] && [[ -f $1 ]]); then
    echo "Error: Either no filename provided or the file does not exist"
    exit 1;
fi

# Replace every null sequence with a new line and then
# break up every sequence of non nulls with a new line
# perl -0777 -pe 's/\0+/\n/g; s/([^\n]{30})/$1\n/g' $1 | bat
perl -0777 -pe 's/([^\n]{30})/$1\n/g; s/\0+//g' $1 | bat
