#!/bin/bash

set -e # Exit on any error

BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
ORANGE='\033[0;33m'
WHITE='\033[0m' # No Color

file1="temp/testFile.txt"
file2="temp/tempFile"

make clean
make debug
echo -e "\n${BLUE}Output of ./out/create_files:${WHITE}"
./out/create_files -n -r 30 -f "$file1"
echo -e "\n${BLUE}Output of ./out/sort_files:${WHITE}"
./out/sort_files -n 5 -b 3 "$file1"
echo -e "\n${ORANGE}State of the temp directory:${WHITE}"
ls temp
echo -e "\n${MAGENTA}Contents of $file1 $file2:${WHITE}"

if [[ -f "$file1" && -f "$file2" ]]; then
    paste -d '|' <(verifyOutput "$file1") <(verifyOutput "$file2") |
        sed 's/|/!│  /g' |
        column -t -s '!' |
        bat --file-name "$file1 $file2" --paging=never
else
    verifyOutput temp/testFile.txt
fi
